name: Harbour for Windows 32 using BCC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    # Only allow repository owner to trigger
    if: github.actor == github.repository_owner

    steps:
    - name: Checkout harbour/core repository
      uses: actions/checkout@v4
      with:
        repository: harbour/core
        path: harbour
        fetch-depth: 1

    - name: Install dependencies
      shell: pwsh
      run: |
        $rawUrl = "https://github.com/woodhead2019/Harbour_builder/raw/master/.github/temp"
        $downloads = @(
          @{Url="$rawUrl/OpenSSL-Win32.zip"; Out="C:\temp\OpenSSL-Win32.zip"; Extract="C:\OpenSSL"},
          @{Url="$rawUrl/curl-7.54.0-win32-mingw.zip"; Out="C:\temp\curl-7.54.0-win32-mingw.zip"; Extract="C:\curl"},
          @{Url="$rawUrl/acesdk.zip"; Out="C:\temp\acesdk.zip"; Extract="C:\acesdk"},
          @{Url="$rawUrl/libcurl.lib"; Out="C:\temp\libcurl.lib"},
          @{Url="$rawUrl/bcc70.zip"; Out="C:\temp\bcc70.zip"; Extract="C:\bcc7"}
        )
        New-Item -Path C:\temp -ItemType Directory -Force
        foreach ($item in $downloads) {
          Invoke-WebRequest -Uri $item.Url -OutFile $item.Out -ErrorAction Stop
          if ($item.Extract) {
            Expand-Archive -Path $item.Out -DestinationPath $item.Extract -Force
          }
        }

    - name: Compile Harbour
      shell: cmd
      env:
        PATH: c:\bcc7\bin;%PATH%
        HB_BUILD_MODE: c
        HB_USER_PRGFLAGS: -l-
        HB_BUILD_CONTRIBS: ""
        HB_WITH_OPENSSL: C:\OpenSSL\include
        HB_WITH_CURL: C:\curl\include
        HB_WITH_ADS: C:\acesdk
        HB_STATIC_OPENSSL: yes
        HB_STATIC_CURL: yes
        HB_COMPILER: bcc
        HB_BUILD_CONTRIB_DYN: no
        HB_BUILD_DYN: no
        HB_USER_RESFLAGS: -Ic:\bcc7\include\windows\sdk\
      run: |
        cd harbour
        win-make.exe

    - name: Create output folders
      shell: cmd
      run: |
        mkdir output\bin output\lib output\include
        copy harbour\bin\win\bcc\*.exe output\bin
        copy harbour\lib\win\bcc\*.lib output\lib
        copy C:\temp\libcurl.lib output\lib
        xcopy harbour\include output\include /E /I /Y

    - name: Get current time
      id: current-time
      shell: pwsh
      run: echo "TIME=$(Get-Date -Format 'yyyyMMdd')" >> $env:GITHUB_ENV

    - name: Upload Harbour artifact
      uses: actions/upload-artifact@v4
      with:
        name: harbour_win32_bcc_${{ env.TIME }}
        path: output/
        retention-days: 7
